cacoinpar/config/routes.rb
Rails.application.routes.draw do

  resources :affiliates, only: [:new, :create]



  root to: 'frontend#index'

  devise_for :users, skip: [:registration]

  mount InyxBlogRails::Engine, :at => '', as: 'post'
  mount InyxPollRails::Engine, :at => '', as: 'poll'
  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  resources :admin, only: [:index]

  scope :admin do
    get 'news/:id', to: "admin#news_show", as: :news_show
    get 'polls/list/questions', to: "admin#polls", as: :polls_question

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :admin do
    resources :affiliates, except: [:new, :create] do
      collection do
        get '/download/:id/:type', to: 'affiliates#download_file', as: :download_attachment
        post '/delete', to: 'affiliates#delete'
      end
    end 
  end
  
end

cacoinpar/app/views/admin/_nav_dashboard.html.haml
%ul.nav.nav-pills.nav-justified#dash-nav{ style: "padding-top:50px;"}
	%li{ class: "#{'active' if action_name == 'index' or action_name == 'news_show'}"}
		= link_to "Noticias", admin_index_path
	%li{ class: "#{'active' if action_name == 'polls'}"}
		= link_to "Encuestas", polls_question_path
		

cacoinpar/app/views/admin/index.html.haml
- if current_user.has_role? :admin
	= content_for(:title, "Administracion - CACOINPAR")
- else 
	= content_for(:title, "Afiliados - CACOINPAR")
- if current_user.has_role? :admin
	.row{style:"width: 100%; margin-top: 50px; padding: 10px; margin-left: 0px; margin-right: 0px;"}
		.col-lg-4.col-md-6.col-sm-6
			.panel-info		
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= Location.all.count
						.title-info
							Visitas
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-eye
		.col-lg-4.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= Affiliate.where(status: "Aprobado").count
						.title-info
							Afiliados
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-users

		.col-lg-4.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= DateTime.now.strftime("%d")
						.title-info
							= DateTime.now.strftime("%B")
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-calendar
= render "nav_dashboard"
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
.news
	.row
		.col-lg-3.col-lg-offset-9
			= form_tag admin_index_path, method: :get, :html => {:class => ""} do |f|
				.input-group
					= text_field_tag :query, params[:query], :placeholder => "Buscar..", class: "form-control"
					%span.input-group-btn
						%button.btn.btn-default
							%i.fa.fa-search
	- if @posts.empty?
		%p{ style: "text-align:center"} No hay posts 
	- @posts.each do |post|
		= link_to news_show_path(post.id), class: "link-post" do
			.post-affiliate
				%h2
					= post.title
				.small
					= "#{post.created_at.strftime("%d %b. %Y")}, #{post.user.name}"
	.center{ style: "text-align:center"}
		= paginate @posts

	

cacoinpar/app/views/admin/news_show.html.haml
= content_for(:title, "Admin - #{@post.title}")

= render "nav_dashboard"
.news
	.row
		.col-lg-3.col-lg-offset-9
			= form_tag admin_index_path, method: :get, :html => {:class => ""} do |f|
				.input-group
					= text_field_tag :query, params[:query], :placeholder => "Buscar..", class: "form-control"
					%span.input-group-btn
						%button.btn.btn-default
							%i.fa.fa-search
	.row{ style: "margin-top:20px;"}
		.col-lg-9.col-xs-12
			%h2.title
				= @post.title
			%p.content
				= @post.content.html_safe
			.pull-right
				= "#{@post.created_at.strftime("%d %b. %Y")}, #{@post.user.name}"
		.col-lg-3.hidden-xs
			%a.twitter-timeline{ href:"https://twitter.com/PARCATUR", "data-widget-id"=>"#{InyxBlogRails.widget_twitter_id}", "data-chrome"=>"header" } Tweets por @PARCATUR

%script{ src: "//platform.twitter.com/widgets.js" }

cacoinpar/app/views/admin/polls.html.haml
= content_for(:title, "Admin - Encuestas")
- if current_user.has_role? :admin
	.row{style:"margin-top: 50px; padding: 10px;"}
		.col-lg-4.col-md-6.col-sm-6
			.panel-info		
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= Location.all.count
						.title-info
							Visitas
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-eye
		.col-lg-4.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= User.all.count
						.title-info
							Usuarios
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-users

		.col-lg-4.col-md-6.col-sm-6
			.panel-info
				.row
					.col-lg-6.col-md-6.col-sm-6.col-xs-6{style:"z-index:1"}
						.number-info
							= DateTime.now.strftime("%d")
						.title-info
							= DateTime.now.strftime("%B")
					.col-lg-6.col-md-6.col-sm-6.col-xs-6			
						.icon-info
							%i.fa.fa-calendar
= render "nav_dashboard"
= render template: "inyx_poll_rails/polls/front_index"