inyx_blog_rails/config/routes.rb
InyxBlogRails::Engine.routes.draw do

  scope :admin do
    get 'angular/category/:id/subcategories', to: 'angular#subcategories'
    get 'angular/posts/:id', to: 'angular#post'
  end


  scope :admin, :blog do
  	resources :posts do
  		collection do
	  		post '/delete', to: 'posts#delete'
	  	end
  	end
  end

  scope :admin, :posts do
    resources :categories do
      collection do
        post '/delete', to: 'categories#delete'
      end
    end
  end

  scope :blog do
    get "/posts/search_posts", to: 'posts#search_posts', as: "search_posts"
    get "/posts/search/:query", to: 'posts#search', as: "posts_front_search"
    get "/posts/:title", to: 'posts#show_front', as: "show_front_posts"
    get "/posts", to: 'posts#index_front', as: "index_front_posts"
    get "/category/:category_permalink/posts", to: "posts#category_front", as: "index_category_posts"
    get "/category/:category_permalink/subcategory/:subcategory_permalink/posts", to: "posts#subcategory_front", as: "index_subcategory_posts"
    get "/tag/:permalink/posts", to: "posts#tag_front", as: "index_tag_posts"
    get "/autor/:permalink/posts", to: "posts#autor_front", as: "index_autor_posts"
  end

end

inyx_blog_rails/app/models/inyx_blog_rails/category.rb
module InyxBlogRails
  require 'elasticsearch/model'
  class Category < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  	before_save :humanize_name, :create_permalink
    validates_uniqueness_of :name
  	has_many :posts, dependent: :destroy
  	has_many :subcategories
  	accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true

  	 
    def as_json(options={})
      {
        id: self.id,
        name: self.name,
        subcategories: self.subcategories.map { |sub| sub.name }.join(", ")
      }
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :subcategories] }  }, sort: { id: "desc" }, size: Post.count }
    end

    def self.get_id(permalink)
	  	Category.find_by_permalink(permalink).id
	  end

	  private

	  def humanize_name
	  	self.name = self.name.humanize
	  end

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

    def self.index(current_user)
      Category.order('created_at DESC')
    end

    def self.index_search(objects, current_user)
      objects.order('created_at DESC')
    end

    def self.index_total(objects, current_user)
      objects.count
    end

    def self.route_index
      "/admin/posts/categories"
    end

    def self.multiple_destroy(ids, current_user)
      ids.each do |id|
        if !current_user.has_role? :admin
          raise CanCan::AccessDenied.new("Access Denied", :delete, InyxBlogRails::Category)
        end
      end
      Category.destroy ids
    end

  end
  Category.import
end

inyx_blog_rails/app/models/inyx_blog_rails/post.rb
module InyxBlogRails
  require 'elasticsearch/model'
  class Post < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    mount_uploader :image, ImageUploader
    belongs_to :user
    belongs_to :category
    belongs_to :subcategory
    acts_as_taggable
    acts_as_taggable_on :tags

    validates_presence_of :title, :content, :category
    validates_uniqueness_of :title

    #before_save :confirmed_public_emails

  	def as_json(options={})
  		{
  			id: self.id,
  			title: self.title,
        title_truncate: self.title.truncate(80),
        image: self.image.url,
  			autor: self.user.name,
        autor_permalink: self.user.permalink,
        autor_id: self.user.id,
        category_name: self.category.nil? ? nil : self.category.name.humanize,
        category_id: self.category_id,
        category_permalink: self.category.nil? ? nil : self.category.permalink,
        subcategory_name: self.subcategory.nil? ? nil : self.subcategory.name,
        subcategory_id: self.subcategory_id,
        subcategory_permalink: self.subcategory.nil? ? nil : self.subcategory.permalink,
        tags: self.tag_list.to_s,
  			content: self.content,
        content_truncate: self.content.truncate(500),
  			public: self.public ? "Publicado" : "Despublicado",
        publicate: self.public,
        comments_open: self.comments_open,
        likes_enabled: self.likes_enabled,
        shared_enabled: self.shared_enabled,
        datetime: self.created_at? ? self.created_at.strftime("%d %b. %Y / %H:%M") : nil,
  			created_at: self.created_at? ? self.created_at.strftime("%b. %Y") : nil,
        day: self.created_at? ? self.created_at.day : nil,
  			updated_at: self.updated_at? ? self.updated_at : nil,
        category: self.category_id.blank? ? nil : Category.find(self.category_id),
        subcategory: self.subcategory.nil? ? nil : Subcategory.find(self.subcategory_id),
        permalink: self.permalink
  		}
  	end

    #def confirmed_public_emails
     # if self.likes_enabled == true and self.public == false
      #  user = User.with_role :afiliado
       # PostMailer.post_email(self, user).deliver_now
      #end
    #end

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:title, :category_name, :public, :content, :autor, :subcategory_name, :tags], operator: :and }  }, sort: { id: "desc" }, size: Post.count }
    end

    def self.index(current_user)
      if current_user.has_role? :redactor
        Post.where(user_id: current_user.id).order('created_at DESC')
      else
        Post.order('created_at DESC')
      end
    end

    def self.index_search(objects, current_user)
      if current_user.has_role? :redactor
        objects.where(user_id: current_user.id).order('created_at DESC')
      else
        objects.order('created_at DESC')
      end
    end

    def self.index_total(objects, current_user)
      if current_user.has_role? :redactor
        objects.where(user_id: current_user.id).count
      else
        objects.order('created_at DESC').count
      end
    end

    def self.route_index
      "/admin/blog/posts"
    end

    def self.multiple_destroy(ids, current_user)
      ids.each do |id|
        if Post.find(id).user_id != current_user.id and !current_user.has_role? :admin
          raise CanCan::AccessDenied.new("Access Denied", :delete, InyxBlogRails::Post)
        end
      end
      Post.destroy ids
    end
    
  end

  Post.import
end

inyx_blog_rails/app/models/inyx_blog_rails/subcategory.rb
module InyxBlogRails
  class Subcategory < ActiveRecord::Base
  	before_save :create_permalink
  	belongs_to :category
  	has_many :posts

  	def self.get_category_id(permalink)
	  	Subcategory.find_by_permalink(permalink).category_id
	  end

	  def self.get_id(permalink)
	  	Subcategory.find_by_permalink(permalink).id
	  end

  	private
	  	def create_permalink
	      self.permalink = self.name.downcase.parameterize
	    end
  end
end

inyx_blog_rails/app/controllers/inyx_blog_rails/angular_controller.rb
require_dependency "inyx_blog_rails/application_controller"

module InyxBlogRails
  class AngularController < ApplicationController

  	def post
  		post = Post.find(params[:id])
  		respond_to do |format|
        format.html
        format.json { render :json => post.as_json }
      end
  	end

    def subcategories
    	subcategories = Subcategory.where(category_id: params[:id])
    	respond_to do |format|
        format.html
        format.json { render :json => subcategories  }
      end
    end

  end
end

inyx_blog_rails/app/controllers/inyx_blog_rails/application_controller.rb
module InyxBlogRails
  class ApplicationController < ::ApplicationController
  end
end

inyx_blog_rails/app/controllers/inyx_blog_rails/categories_controller.rb
require_dependency "inyx_blog_rails/application_controller"

module InyxBlogRails
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
    load_and_authorize_resource
    layout 'admin/application'

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'La categoría ha sido creada satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        @category.__elasticsearch__.index_document
        redirect_to @category, notice: 'La categoría ha sido actualizada satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'La categoría ha sido eliminada satisfactoriamente.'
    end


    private
    
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, subcategories_attributes: [:id, :name, :_destroy])
      end
  end
end

inyx_blog_rails/app/controllers/inyx_blog_rails/posts_controller.rb
require_dependency "inyx_blog_rails/application_controller"

module InyxBlogRails
  class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!, except: [:show_front, :index_front, :category_front, :subcategory_front, :tag_front, :autor_front, :search, :search_posts]
    layout :resolve_layout
    load_and_authorize_resource :except => [:index_front, :show_front, :search, :search_posts, :category_front, :subcategory_front, :autor_front, :tag_front]



    def search_posts 
      unless params[:query].blank?
        redirect_to posts_front_search_path(params[:query])
      else
        redirect_to index_front_posts_path
      end
    end

    def search
      @posts = Post.search(Post.query params[:query]).records.where(public: true, likes_enabled: false).order('created_at DESC').limit(5).offset(params[:offset])
      @categories = Category.order(:name).all
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    # GET /posts/1
    def show
      respond_to do |format|
        format.html
        format.json { render :json => @post.category_form }
      end
    end

    def show_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      @post = Post.where(permalink: params[:title], likes_enabled: false).first
      @categories = Category.order(:name).all
      respond_to do |format|
        unless @post.nil?
          format.html
          format.json { render :json => nil }
        else
          format.html do
            redirect_to index_front_posts_path
          end
        end
      end
    end

    def index_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      @posts = Post.where(public: true, likes_enabled: false).order('created_at DESC').limit(5).offset(params[:offset])
      @categories = Category.order(:name).all
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    def category_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      @categories = Category.order(:name).all
      @posts = Post.where(category_id: Category.get_id(params[:category_permalink]), public: true, likes_enabled: false).order('created_at DESC').limit(5).offset(params[:offset])
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    def subcategory_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      category = Category.find_by_permalink(params[:category_permalink])
      subcategory = category.subcategories.find_by_permalink(params[:subcategory_permalink])
      @posts = Post.where(subcategory_id: subcategory.id, public: true, likes_enabled: false).order('created_at DESC').limit(5).offset(params[:offset])
      @categories = Category.order(:name).all
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    def tag_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      @posts = Post.where(public: true, likes_enabled: false).tagged_with(params[:permalink].gsub("-", " ")).order('created_at DESC');
      @categories = Category.order(:name).limit(5).offset(params[:offset])
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    def autor_front
      @recents = Post.where(public: true, likes_enabled: false).order("created_at DESC").limit(5)
      @posts = Post.where(user_id: User.get_id(params[:permalink], likes_enabled: false), public: true).order('created_at DESC').limit(5).offset(params[:offset])
      @categories = Category.order(:name).all
      respond_to do |format|
        format.html
        format.json { render :json => @posts }
      end
    end

    # GET /posts/new
    def new
      @categories = Category.all
      @post = Post.new
      @subcategories = Category.find(@post.category_id).subcategories if @post.created_at?
    end

    # GET /posts/1/edit
    def edit
      @subcategories = Category.find(@post.category_id).subcategories
      @categories = Category.all
    end

    # POST /posts
    def create
      @categories = Category.all
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save
        redirect_to @post, notice: 'El post ha sido creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        @post.__elasticsearch__.index_document
        redirect_to @post, notice: 'El post ha sido actualizado satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'El post ha sido eliminado satisfactoriamente.'
    end
 
    private

      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :content, :image, :public, :comments_open, :likes_enabled, :shared_enabled, :tag_list, :category_id, :subcategory_id, :permalink)
      end

      def resolve_layout
        case action_name
          when "show_front", "index_front", "category_front", "subcategory_front", "tag_front", "autor_front", "search_posts", "search"
            "inyx_blog_rails/frontend/application"
          else 
            "admin/application"
        end
      end

  end
end

inyx_blog_rails/app/helpers/inyx_blog_rails/angular_helper.rb
module InyxBlogRails
  module AngularHelper
  end
end

inyx_blog_rails/app/helpers/inyx_blog_rails/application_helper.rb
module InyxBlogRails
  module ApplicationHelper
  end
end

inyx_blog_rails/app/helpers/inyx_blog_rails/categories_helper.rb
module InyxBlogRails
  module CategoriesHelper
  end
end

inyx_blog_rails/app/helpers/inyx_blog_rails/posts_helper.rb
module InyxBlogRails
  module PostsHelper
  end
end

inyx_blog_rails/app/views/layouts/inyx_blog_rails/blog/_navbar_categories.html.haml
%nav.navbar.navbar-default#navbar-categories
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - @categories.each do |category|
          %li.dropdown
            = link_to({ controller: "posts", action: "category_front", category_permalink: category.permalink }, class: "dropdown-toggle disabled", "aria-expanded" => "false", "data-toggle" => "dropdown", :role => "button") do
              = category.name
              %span.caret
            - unless category.subcategories.empty?
              %ul.dropdown-menu{:role => "menu"}
                - category.subcategories.each do |subcategory|
                  %li
                    = link_to subcategory.name, index_subcategory_posts_path(category.permalink, subcategory.permalink)

inyx_blog_rails/app/views/layouts/inyx_blog_rails/blog/_post.html.haml
.col-lg-9.col-md-9.col-sm-9.col-xs-12
	.post
		.preview-post.row{ "ng-if" => "posts.publicate == true"}
			.col-lg-9.col-md-9.col-sm-9.col-xs-12
				%h4.title-post
					= link_to "{{ posts.title | uppercase }}", "/blog/posts/{{post.permalink}}"
				.image-post{ "ng-if" => "posts.image" }
					%img.thumbnail{ "ng-src" => "{{posts.image}}", alt: "{{posts.title}}", title: "{{posts.title}}" }
				.content-post{ "ng-bind-html" => "content_html(posts.content)", style: "text-align:justify;"}
				.row.socials{ "ng-if" => "posts.shared_enabled == true" }
					.col-sm-12.col-md-12.col-sm-12.col-xs-12.socials-shared{ style: "margin-bottom: 15px;"}
						.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-facebook
							#fb-root
								.fb-like{"data-action" => "like", "data-href" => "#{request.url}", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
						.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-gplus
							.g-plus{"data-action"=>"share", "data-annotation"=>"bubble"}
						.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-twitter
							= link_to "Twittear", "https://twitter.com/share", class: "twitter-share-button", "data-lang" => "es", "data-text" => "#parcatur #{@post.title}", "data-url" => "#{request.url}", "data-via" => "parcatur"
						
				.comments{ "ng-if" => "posts.comments_open == true" }
					#fb-root{ style: "margin-bottom:15px;"}
						.fb-comments{ 'data-href' => "#{request.url}",  'data-numposts' => "8", 'data-colorscheme' => "light", "data-width" => "100%" }
			.col-lg-3.col-md-3.col-sm-3.col-xs-12
				%span.date
					{{posts.day}}
					%small
						{{posts.created_at}}
				%span.info
					%span.block
						%i.fa.fa-user
						POR
						= link_to "{{posts.autor | uppercase}}", "/blog/autor/{{posts.autor_permalink}}/posts"
					%span.block
						%i.fa.fa-folder-open-o
						POSTEADO EN
						= link_to "{{posts.category_name | uppercase}}", "/blog/category/{{posts.category_permalink}}/posts"
					%span.block
						%i.fa.fa-link
						= link_to "PERMALINK", "/blog/posts/{{posts.permalink}}"

%script{ src:"//platform.twitter.com/widgets.js" }

- if @post.shared_enabled

	:javascript
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		
		//facebook share
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

		//google+ share
		window.___gcfg = {lang: 'es'};

		(function() {
			var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			po.src = 'https://apis.google.com/js/platform.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		})();

		//chat-comment-facebook
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.0";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

inyx_blog_rails/app/views/layouts/inyx_blog_rails/blog/_posts_list.html.haml
.col-lg-9.col-md-9.col-sm-9.col-xs-12
	.post{ "ng-repeat" => "post in posts" }
		.preview-post.row
			.col-lg-9.col-md-9.col-sm-9.col-xs-12
				%h4.title-post
					= link_to "{{ post.title | uppercase }}", "/blog/posts/{{post.permalink}}"
				.image-post{ "ng-if" => "post.image" }
					%img.thumbnail{ "ng-src" => "{{post.image}}", alt: "{{post.title}}", title: "{{post.title}}" }
				.content-post{ "ng-bind-html" => "content_html(post.content_truncate)", style: "text-align:justify;"}
				.read-more.pull-right
					= link_to "/blog/posts/{{post.permalink}}" do
						%i.fa.fa-sign-out
						LEER MÁS
			.col-lg-3.col-md-3.col-sm-3.col-xs-12
				%span.date
					{{post.day}}
					%small
						{{post.created_at}}
				%span.info
					%span.block
						%i.fa.fa-user
						POR
						= link_to "{{post.autor | uppercase}}", "/blog/autor/{{post.autor_permalink}}/posts"
					%span.block
						%i.fa.fa-folder-open-o
						POSTEADO EN
						= link_to "{{post.category_name | uppercase}}", "/blog/category/{{post.category_permalink}}/posts"
					%span.block
						%i.fa.fa-link
						= link_to "PERMALINK", "/blog/posts/{{post.permalink}}"

inyx_blog_rails/app/views/layouts/inyx_blog_rails/blog/_sidebar_left.html.haml
.col-lg-3.col-md-3.col-sm-3.col-xs-12
	= render "inyx_blog_rails/posts/widgets/search"
	= render "inyx_blog_rails/posts/widgets/recents"
	= render "inyx_blog_rails/posts/widgets/categories"
	= render "inyx_blog_rails/posts/widgets/tags"
	= render "inyx_blog_rails/posts/widgets/timeline_twitter"