cacoinpar/config/routes.rb
Rails.application.routes.draw do

  resources :affiliates, only: [:new, :create]



  root to: 'frontend#index'

  devise_for :users, skip: [:registration]

  mount InyxBlogRails::Engine, :at => '', as: 'post'
  mount InyxPollRails::Engine, :at => '', as: 'poll'
  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'

  resources :admin, only: [:index]

  scope :admin do
    get 'news/:id', to: "admin#news_show", as: :news_show
    get 'polls/list/questions', to: "admin#polls", as: :polls_question

  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end

  scope :admin do
    resources :affiliates, except: [:new, :create] do
      collection do
        get '/download/:id/:type', to: 'affiliates#download_file', as: :download_attachment
        post '/delete', to: 'affiliates#delete'
      end
    end 
  end
  
end

cacoinpar/app/views/inyx_poll_rails/categories/_form.html.haml
= simple_form_for(@category) do |f|
  .container_form 
    .title_form
      Datos de Categoría
    .form-inyx
      = f.input :name, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Nombre" }
      = f.input :description, label: false, input_html: { class: 'form-control input-inyx', placeholder: "Descripción"}
    .panel-footer
      .form-actions
        = f.button :submit, "Guardar", class: "pull-right btn submit-inyx"
      .clearfix

cacoinpar/app/views/inyx_poll_rails/categories/_view_lg_md.html.haml
%div{ 'ng-init'=>"init(#{@objects.to_json}, '/admin/polls/categories', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => "" }
	.grid-content
		.col-lg-9.col-md-9{ style: "padding:0px;" }	
			.list-wrapper
				.panel.panel-default
					- flash.each do |name, msg|
						- if msg.is_a?(String)
							%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
								%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
								= content_tag :div, msg, :id => "flash_#{name}"
					.panel-heading#list-heading
						- if can? :new, User
							= link_to new_category_path, title: t("admin.buttons.new"), class: "btn btn-default btn-action" do
								%i.fa.fa-plus
						%a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
							%i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
							%i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
						- if can? :delete, User
							%a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
								%i.fa.fa-square-o{"ng-show" => "!btnDelete"}
								%i.fa.fa-check-square-o{ "ng-show" => "btnDelete" }	
							%a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las categorias seleccionadas?, esta acción eliminará todas las encuestas pertenecientes a ellas.')", :title => t("admin.buttons.trash") }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
								%i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
						.paginator.pull-right{ "ng-show" => "objects.length > 0"}
							%button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
								Página {{currentPage+1}} de {{numberOfPages()}}
							%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
								%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
							%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
								%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
								%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
					.panel-body{ style: "border-right: 1px solid #e7e7e7;" }
						#table-scroll
							%table.grid{style: "width:100%"}
								%tbody
									%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
										- if can? :delete, User
											%td{ width: "1px;" }
												.checkboxFour
													%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
													%label{ for: "check-{{object.id}}" }
														%span
										%td {{ object.name }}
										%td {{ object.description }}
										
									%tr{"ng-show" => "!objects.length"}
										%td{:style => "width:100%"}
											%center
												%i.fa.fa-frown-o
												No hay Categorías.
			
		.col-lg-3.col-md-3{ style: "padding:0px;"}
			.show-wrapper
				.show-head
				.show-body
					.panel.panel-default
						.panel-heading{ style: "height:55px;" }
							.actions{ "ng-show" => "object_data" }
								.title.pull-left{ style: "margin-top:6px;" }
									%i.fa.fa-user
									Categoría - {{ object_data.id }}
								- if can? :destroy, User
									= link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta categoría?, Esta acción eliminará todas las encuestas pertenecientes a ella.' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
										%i.fa.fa-remove
								- if can? :edit, User
									= link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
										%i.fa.fa-pencil
							.actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
								%i.fa.fa-tags
								Categoría
						.panel-body
							.data{ style: "height: {{windowHeight-104}}px;" }
								.attributes{ "ng-show" => "object_data" }
									%label Nombre: 
									{{object_data.name}}
									%br
									%label Descripción: 
									{{object_data.description}}
								.attributes{ "ng-show" => "!object_data"}
									%center
										No se ha seleccionado una categoría para mostrar.
				.show-footer

cacoinpar/app/views/inyx_poll_rails/categories/_view_sm_xs.html.haml
- if can? :new, User
	= link_to new_category_path, class: "float-button" do
		%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					- if can? :delete, User
						%td{ width: "1px;" }
							.checkboxFour
								%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
								%label{ for: "check-{{object.id}}" }
									%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name }}
					%td 
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.description }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay Categorias.

cacoinpar/app/views/inyx_poll_rails/categories/edit.html.haml
= content_for(:title, "Admin - Encuestas - Categorias | Editar")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

cacoinpar/app/views/inyx_poll_rails/categories/index.html.haml
= content_for(:title, "Admin - Polls - Categorias")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

cacoinpar/app/views/inyx_poll_rails/categories/new.html.haml
= content_for(:title, "Admin - Encuestas - Categorias | Nuevo")

%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

cacoinpar/app/views/inyx_poll_rails/categories/show.html.haml
= content_for(:title, "Admin - Categorías | #{@category.name}")
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div.hidden-xs{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", id:"message_alerts"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			= content_tag :div, msg, :id => "flash_#{name}"
%div
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{style:"padding-top:5px"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-tags
					Categoría - 
					= @category.id
				- if can? :destroy, User
					= link_to category_path(@category), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta categoría?, esta acción eliminará todas las encuestas pertenecientes a ellas.' }, class: "btn btn-default btn-action pull-right" do
						%i.fa.fa-remove
				- if can? :edit, User
					= link_to  edit_category_path(@category), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
						%i.fa.fa-pencil		

		.panel-body#body-show
			%label Nombre
			= @category.name
			%br/
			%label Descripción
			= @category.description